### ISSUE TITLE
Wierd scroll effect

### ISSUE THREAD

**Issue by Transito-SG** [TechSupportz/transito-flutter#21]
**Describe the bug**
  When scrolling in favourite page with multiple favourites which overflow screen, scrolling is not smooth and will jump to certain paths of the screen
  
  **To Reproduce**
  Go to favorite screen with a lot of favourites then scroll
  
  **Expected behavior**
  Should scroll amoothly
  
  **Screenshots**
None
  
  **Smartphone (please complete the following information):**
  - Device: iPhone 13
  - OS: iOS | Idk
  - App Version: Idk

  **Additional context**
  Idk

  Reported by someone who takes public transport

**Comment by TechSupportz** [comment]
This issue should be fixed for _most_ situations.

**Cause:**
Favourites cards being de-rendered when its off screen and when being re-rendered the bus timings popping in caused some jank when scrolling up

**Fix**
Increased the cache extent so the cards should not get de-rendered as easily as before
