### ISSUE TITLE
Empty Favourite

### ISSUE THREAD

**Issue by DenouementD** [TechSupportz/transito-flutter#8]
When you favourite a Bus Stop and click on save changes without selecting a Bus Service, an empty table with the selected Bus Stop will appear as the title

**To Reproduce**
1. Click on any Bus Stop
2. Click on the Favourite button (Heart Icon)
3. Click on "Add to favourites"
4. Switch to the Favourites tab
5. Scroll to the selected Bus Stop
6. The error appears

**Expected behavior**
Favourite should not be added to the Favourites tab

**Smartphone (please complete the following information):**
 - Device: Samsung S22 Ultra
 - OS: Android 12
 - App Version: v1.1.1

**Comment by TechSupportz** [comment]
Thank you for pointing out this bug! Fixed it in https://github.com/TechSupportz/transito-flutter/commit/eb370b64276d844bc7d06a0f2200d8bd98bf8a87
